# Generated by Django 2.2.3 on 2019-07-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityfield',
            old_name='name',
            new_name='city',
        ),
    ]
