# Generated by Django 2.2.3 on 2019-08-31 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190730_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfield',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'Only alpha letters characters are allowed.')]),
        ),
    ]
